import type { Metadata } from "next";
import "../globals.css";
import { kanit } from "../fonts";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className}`}>
        {children}
        <Toaster richColors position="bottom-center" />
      </body>
    </html>
  );
}
