import type { Metadata } from "next";
import "./globals.css";
import { kanit } from "./fonts";

export const metadata: Metadata = {
  title: "ThaNaDev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className}`}>{children}</body>
    </html>
  );
}
