import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import DLayout from "./dashboard/components/DLayout";
import { kanit } from "../../fonts";
import "../../globals.css";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className}`}>
        <DLayout>{children}</DLayout>
        <Toaster richColors position="bottom-center" />
      </body>
    </html>
  );
}
