import type { Metadata } from "next";
import "../../globals.css";
import { kanit } from "../../fonts";
import { Toaster } from "@/components/ui/sonner";
import { getLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body className={`${kanit.className}`}>
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
        <Toaster richColors position="bottom-center" />
      </body>
    </html>
  );
}
